Feat: Update Publish-* methods for JSON generation
vmware/powershell-module-for-vmware-cloud-foundation-reporting pull request #79
Opened 2023-01-25 18:18 UTC by bhumitra

Signed-off-by: bhumitra nagar <bnagar@vmware.com>

In order to have a good experience with our community, we recommend that you read the [contributing guidelines](https://github.com/vmware/powershell-module-for-cloud-foundation-reorting/blob/main/CONTRIBUTING_DCO.md) for making a pull request.

**Summary of Pull Request**

Updated Publish-* cmdlets to support json generation for -
Publish-BackupStatus
Publish-NsxtTransportNodeStatus
Publish-NsxtTier0BgpStatus
Publish-SnapshotStatus
Publish-LocalUserExpiry
Publish-StorageCapacityHealth

Added 2 new methods -
Publish-NsxtHealthNonSOS
Publish-ComponentConnectivityHealthNonSOS

**Type of Pull Request**

- [ ] This is a bug fix.
- [x] This is an enhancement or feature.
- [ ] This is a code style / formatting update.
- [ ] This is a documentation update.
- [ ] This is a refactoring update.
- [ ] This is a chore update
- [ ] This is something else.
      Please describe:

**Related to Existing Issues**

Issue Number: 37

**Test and Documentation Coverage**

- [x] Tests have been completed (for bug fixes / features).
- [ ] Documentation has been added / updated (for bug fixes / features).

**Breaking Changes?** 

- [x] Yes, there are breaking changes.
- [ ] No, there are no breaking changes.

New if/else path has been added to these cmdlets. if called using -jsonOutput, then json is generated. Else, the functionality is the same as before. I have tested the functionality and it works fine.

2023-01-25 18:55 UTC, tenthirtyam commented
Hi @bhumitra -

I’ve marked the pull request for the `v1.1.0` milestone release planned for February 2023. We will hold the merging of this pull request until after the `v1.0.6` milestone release for January 2023. Reviews will, however, occur soon. 🚀 

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

2023-01-31 19:43 UTC, tenthirtyam requested changes
Minor changes requestion on first pass:

- Other examples and the README.md use `F:\Reporting` vs `F:\Reports`. Added suggestions to keep them consistent.
- Use `-Depth` vs `-depth`.
- Minor grammatical suggestions.

2023-01-31 19:43 UTC, tenthirtyam commented on VMware.CloudFoundation.Reporting.psm1
> +        Publish-BackupStatus -server sfo-vcf01.sfo.rainpole.io -user admin@local -pass VMw@re1!VMw@re1! -allDomains -outputJson F:\Reports
```suggestion
        Publish-BackupStatus -server sfo-vcf01.sfo.rainpole.io -user admin@local -pass VMw@re1!VMw@re1! -allDomains -outputJson F:\Reporting
```

2023-01-31 19:43 UTC, tenthirtyam commented on VMware.CloudFoundation.Reporting.psm1
> +        and save it under F:\Reports with filename <timestamp>-backup-status.json
```suggestion
        and save it under F:\Reporting with filename <timestamp>-backup-status.json
```

2023-01-31 19:43 UTC, tenthirtyam commented on VMware.CloudFoundation.Reporting.psm1
> +        Publish-NsxtTransportNodeStatus -server sfo-vcf01.sfo.rainpole.io -user admin@local -pass VMw@re1!VMw@re1! -allDomains
```suggestion
        Publish-NsxtTransportNodeStatus -server sfo-vcf01.sfo.rainpole.io -user admin@local -pass VMw@re1!VMw@re1! -allDomains -outputJson F:\Reports
```

2023-01-31 19:43 UTC, tenthirtyam commented on VMware.CloudFoundation.Reporting.psm1
> +        and save it under F:\Reports with filename <timestamp>-nsxttransportnode-status.json
```suggestion
        and save it under F:\Reporting with filename <timestamp>-nsxttransportnode-status.json
```

2023-01-31 19:43 UTC, tenthirtyam commented on VMware.CloudFoundation.Reporting.psm1
> +        Publish-NsxtTransportNodeTunnelStatus -server sfo-vcf01.sfo.rainpole.io -user admin@local -pass VMw@re1!VMw@re1! -allDomains -outputJson F:\Reports
```suggestion
        Publish-NsxtTransportNodeTunnelStatus -server sfo-vcf01.sfo.rainpole.io -user admin@local -pass VMw@re1!VMw@re1! -allDomains -outputJson F:\Reporting
```

2023-01-31 19:43 UTC, tenthirtyam commented on VMware.CloudFoundation.Reporting.psm1
> +        and save it under F:\Reports with filename <timestamp>-nsxttntunnel-status.json
```suggestion
        and saves it under F:\Reporting with filename <timestamp>-nsxttntunnel-status.json
```

2023-01-31 19:43 UTC, tenthirtyam commented on VMware.CloudFoundation.Reporting.psm1
> +        Publish-NsxtTier0BgpStatus -server sfo-vcf01.sfo.rainpole.io -user admin@local -pass VMw@re1!VMw@re1! -allDomains -outputJson F:\Reports
```suggestion
        Publish-NsxtTier0BgpStatus -server sfo-vcf01.sfo.rainpole.io -user admin@local -pass VMw@re1!VMw@re1! -allDomains -outputJson F:\Reporting
```

2023-01-31 19:43 UTC, tenthirtyam commented on VMware.CloudFoundation.Reporting.psm1
> +        and save it under F:\Reports with filename <timestamp>-nsxttier0bgp-status.json
```suggestion
        and saves it under F:\Reporting with filename <timestamp>-nsxttier0bgp-status.json
```

2023-01-31 19:43 UTC, tenthirtyam commented on VMware.CloudFoundation.Reporting.psm1
> +        Publish-SnapshotStatus -server sfo-vcf01.sfo.rainpole.io -user admin@local -pass VMw@re1!VMw@re1! -allDomains -outputJson F:\Reports
```suggestion
        Publish-SnapshotStatus -server sfo-vcf01.sfo.rainpole.io -user admin@local -pass VMw@re1!VMw@re1! -allDomains -outputJson F:\Reporting
```

2023-01-31 19:43 UTC, tenthirtyam commented on VMware.CloudFoundation.Reporting.psm1
> +        and save it under F:\Reports with filename <timestamp>-snapshot-status.json
```suggestion
        and saves it under F:\Reporting with filename <timestamp>-snapshot-status.json
```

2023-01-31 19:43 UTC, tenthirtyam commented on VMware.CloudFoundation.Reporting.psm1
> +        Publish-LocalUserExpiry -server sfo-vcf01.sfo.rainpole.io -user admin@local -pass VMw@re1!VMw@re1! -sddcRootPass VMw@re1! -allDomains -outputJson F:\Reports
```suggestion
        Publish-LocalUserExpiry -server sfo-vcf01.sfo.rainpole.io -user admin@local -pass VMw@re1!VMw@re1! -sddcRootPass VMw@re1! -allDomains -outputJson F:\Reporting
```

2023-01-31 19:43 UTC, tenthirtyam commented on VMware.CloudFoundation.Reporting.psm1
> +        and save it as a json under F:\Reports with filename <timestamp>-localuserexpiry-status.json
```suggestion
        and saves it under F:\Reporting with filename <timestamp>-localuserexpiry-status.json
```

2023-01-31 19:43 UTC, tenthirtyam commented on VMware.CloudFoundation.Reporting.psm1
> +        Publish-NsxtHealthNonSOS -server sfo-vcf01.sfo.rainpole.io -user admin@local -pass VMw@re1!VMw@re1! -allDomains -outputJson F:\Reports
```suggestion
        Publish-NsxtHealthNonSOS -server sfo-vcf01.sfo.rainpole.io -user admin@local -pass VMw@re1!VMw@re1! -allDomains -outputJson F:\Reporting
```

2023-01-31 19:43 UTC, tenthirtyam commented on VMware.CloudFoundation.Reporting.psm1
> +        saves it as a JSON to file under F:\Reports\<timestamp>-nsxtcombinedhealthnonsos-status.json
```suggestion
       and saves it as JSON under F:\Reporting with filename <timestamp>-nsxtcombinedhealthnonsos-status.json
```

2023-01-31 19:43 UTC, tenthirtyam commented on VMware.CloudFoundation.Reporting.psm1
> +        Publish-StorageCapacityHealth -server sfo-vcf01.sfo.rainpole.io -user admin@local -pass VMw@re1!VMw@re1! -rootPass VMw@re1! -workloadDomain sfo-w01 -outputJson F:\Reports
```suggestion
        Publish-StorageCapacityHealth -server sfo-vcf01.sfo.rainpole.io -user admin@local -pass VMw@re1!VMw@re1! -rootPass VMw@re1! -workloadDomain sfo-w01 -outputJson F:\Reporting
```

2023-01-31 19:43 UTC, tenthirtyam commented on VMware.CloudFoundation.Reporting.psm1
> +        and save it as a json under F:\Reports with filename <timestamp>-storagecapacityhealth-status.json
```suggestion
        and saves it as JSON under F:\Reporting with filename <timestamp>-storagecapacityhealth-status.json
```

2023-01-31 19:43 UTC, tenthirtyam commented on VMware.CloudFoundation.Reporting.psm1
> +		and saves it as JSON under F:\Reporting\<timestamp>-componentconnectivityhealthnonsos-status.json
```suggestion
		and saves it under F:\Reporting with filename <timestamp>-componentconnectivityhealthnonsos-status.json
```

2023-01-31 19:43 UTC, tenthirtyam commented on VMware.CloudFoundation.Reporting.psm1
> +
Extra line break?

2023-01-31 19:43 UTC, tenthirtyam commented on VMware.CloudFoundation.Reporting.psm1
> +Export-ModuleMember -Function Start-CreateOutputJsonDirectory
Does the need to be exported - looks like it's just an internal function.

2023-01-31 19:43 UTC, tenthirtyam commented on VMware.CloudFoundation.Reporting.psm1
> +                    $allBackupStatusObject | ConvertTo-JSON -depth 10 | Out-File $json
```suggestion
                    $allBackupStatusObject | ConvertTo-JSON -Depth 10 | Out-File $json
```

2023-01-31 19:43 UTC, tenthirtyam commented on VMware.CloudFoundation.Reporting.psm1
> +                    $allNsxtTransportNodeStatusObject | ConvertTo-JSON -depth 10 | Out-File $json
```suggestion
                    $allNsxtTransportNodeStatusObject | ConvertTo-JSON -Depth 10 | Out-File $json
```

2023-01-31 19:43 UTC, tenthirtyam commented on VMware.CloudFoundation.Reporting.psm1
> +                    $allNsxtTransportNodeTunnelStatusObject | ConvertTo-JSON -depth 10 | Out-File $json
```suggestion
                    $allNsxtTransportNodeTunnelStatusObject | ConvertTo-JSON -Depth 10 | Out-File $json
```

2023-01-31 19:43 UTC, tenthirtyam commented on VMware.CloudFoundation.Reporting.psm1
> +                    $allNsxtTier0BgpStatusObject | ConvertTo-JSON -depth 10 | Out-File $json
```suggestion
                    $allNsxtTier0BgpStatusObject | ConvertTo-JSON -Depth 10 | Out-File $json
```

2023-01-31 19:43 UTC, tenthirtyam commented on VMware.CloudFoundation.Reporting.psm1
> +                    $allSnapshotStatusObject | ConvertTo-JSON -depth 10 | Out-File $json
```suggestion
                    $allSnapshotStatusObject | ConvertTo-JSON -Depth 10 | Out-File $json
```

2023-01-31 19:43 UTC, tenthirtyam commented on VMware.CloudFoundation.Reporting.psm1
> +            $allPasswordExpiryObject | ConvertTo-JSON -depth 10 | Out-File $json
```suggestion
            $allPasswordExpiryObject | ConvertTo-JSON -Depth 10 | Out-File $json
```

2023-01-31 19:43 UTC, tenthirtyam commented on VMware.CloudFoundation.Reporting.psm1
> +            $allNsxtHealthObject | ConvertTo-JSON -depth 10 | Out-File $json
```suggestion
            $allNsxtHealthObject | ConvertTo-JSON -Depth 10 | Out-File $json
```

2023-01-31 19:43 UTC, tenthirtyam commented on VMware.CloudFoundation.Reporting.psm1
> +                    $combinedJson | ConvertTo-JSON -depth 10 | Out-File $json
```suggestion
                    $combinedJson | ConvertTo-JSON -Depth 10 | Out-File $json
```

2023-01-31 19:43 UTC, tenthirtyam commented on VMware.CloudFoundation.Reporting.psm1
> +            $allConnectivityObject | ConvertTo-JSON -depth 10 | Out-File $json
```suggestion
            $allConnectivityObject | ConvertTo-JSON -Depth 10 | Out-File $json
```

2023-01-31 19:57 UTC, tenthirtyam commented on VMware.CloudFoundation.Reporting.psm1
> +Export-ModuleMember -Function Start-CreateOutputJsonDirectory
```suggestion
```

2023-02-01 15:28 UTC, bhumitra commented on VMware.CloudFoundation.Reporting.psm1
> +        and save it under F:\Reports with filename <timestamp>-backup-status.json
```suggestion
        and saves it under F:\Reporting with filename <timestamp>-backup-status.json
```

2023-02-01 15:30 UTC, bhumitra commented on VMware.CloudFoundation.Reporting.psm1
> +        and save it under F:\Reports with filename <timestamp>-nsxttransportnode-status.json
```suggestion
        and saves it under F:\Reporting with filename <timestamp>-nsxttransportnode-status.json
```

2023-02-02 20:47 UTC, bhumitra commented on VMware.CloudFoundation.Reporting.psm1
> +        and save it under F:\Reports with filename <timestamp>-backup-status.json
```suggestion
        and saves it under F:\Reporting with filename <timestamp>-backup-status.json
```

2023-02-02 20:51 UTC, bhumitra commented on VMware.CloudFoundation.Reporting.psm1
> +
```suggestion
```

2023-02-02 20:57 UTC, tenthirtyam commented on VMware.CloudFoundation.Reporting.psm1
> +        Publish-NsxtTransportNodeStatus -server sfo-vcf01.sfo.rainpole.io -user admin@local -pass VMw@re1!VMw@re1! -allDomains -outputJson F:\Reports
Reporting

2023-02-02 21:21 UTC, tenthirtyam commented
Thanks for committing the review suggestions. 

I’ll give in a flurry of tests tomorrow and report back.

2023-02-03 21:00 UTC, tenthirtyam commented on VMware.CloudFoundation.Reporting.psm1
> +        Publish-NsxtTransportNodeStatus -server sfo-vcf01.sfo.rainpole.io -user admin@local -pass VMw@re1!VMw@re1! -allDomains -outputJson F:\Reports
```suggestion
        Publish-NsxtTransportNodeStatus -server sfo-vcf01.sfo.rainpole.io -user admin@local -pass VMw@re1!VMw@re1! -allDomains -outputJson F:\Reporting
```

2023-02-03 21:22 UTC, tenthirtyam approved these changes
LGTM! 🚀

2023-02-03 21:26 UTC, merged